---
- src: pacifica.ansible_drupalsolr
  version: v1.0.0
- src: pacifica.ansible_drupalvm
  version: v0.2.0
- src: pacifica.ansible_pacifica
  version: v0.3.1
- src: geerlingguy.postgresql
  version: 2.2.0
- src: geerlingguy.redis
  version: 1.6.0
